# Generated by Django 2.2.16 on 2020-10-12 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='city',
            field=models.CharField(max_length=30, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='company_name',
            field=models.CharField(max_length=30, verbose_name='Nombre de la compañia'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='document',
            field=models.CharField(max_length=30, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='lastname',
            field=models.CharField(max_length=30, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de realización'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='event',
            name='site',
            field=models.CharField(max_length=30, verbose_name='Lugar de realización'),
        ),
    ]
